### PR TITLE
add coco mask dataloader

### PR DESCRIPTION
**Pull request by lzx1413**

### CODE REVIEW

**Comment by skrish13** [comment]
@lzx1413, there are few errors...

>   File "train_val.py", line 28, in <module>
>     from preprocess.data_center import CocoDataset,det_mask_collate,NormalizeImage
>   File "/home/ubuntu/maskrcnn/preprocess/data_center.py", line 20, in <module>
>     from lib.pycocotools.coco import COCO
>   File "/home/ubuntu/maskrcnn/lib/pycocotools/coco.py", line 55, in <module>
>     from . import mask as maskUtils
>   File "/home/ubuntu/maskrcnn/lib/pycocotools/mask.py", line 4, in <module>
>     from . import _mask
> ImportError: cannot import name _mask
> 

did you forget to add some files to the commit?

**Comment by lzx1413** [comment]
You should build the pycoco tools firstly in the lib folder.

**Comment by skrish13** [comment]
wouldn't assuming that the user will build it globally (as a python package) be better off?

**Comment by lzx1413** [comment]
Yes, I will update the readme.Thanks for your suggestion.

**Pull request merged**
